echo "/*====*/"
echo "//"
echo "// Version file for "`cat product`
echo "//"
echo "/*----*/"
echo ""
echo "#ifndef __VERSION_H__"
echo "#define __VERSION_H__"
echo ""
echo "using namespace "`cat namespace`";"
echo ""
echo ""
echo "/*----*/"
echo ""
echo "namespace "`cat namespace`
echo "{"
echo ""
echo "#define sVERSION "\"`cat version`\"
echo "#define sPRODUCT "\"`cat product`" "`cat version`\"
echo "#define sAUTHOR "\"`cat author`\"
echo "#define sAUTHOR_LONG "\"`cat author`" <"`cat email`">\""
echo "#define sCOPYRIGHT "\"`cat copyright`" "`cat author`\"
echo "#define sURL "\"`cat url`\"
echo ""
echo ""
echo "/*----*/"
echo ""
echo "} // namespace"`cat namespace`
echo ""
echo "#endif /* __VERSION_H__ */"